export default {
  id: "ollama",
  priority: 30,
  hasFree: true,
  alias: "ollama",
  display: {
    name: "Ollama Cloud",
    icon: "cloud",
    color: "#ffffffff",
    textIcon: "OL",
    website: "https://ollama.com",
    notice: {
      text: "Free tier: light usage, 1 cloud model at a time (limits reset every 5h & 7d). Pro $20/mo · Max $100/mo.",
      apiKeyUrl: "https://ollama.com/settings/keys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://ollama.com/api/chat",
    validateUrl: "https://ollama.com/api/tags",
    format: "ollama",
  },
  models: [
    { id: "gpt-oss:120b", name: "GPT OSS 120B" },
    { id: "gpt-oss:20b", name: "GPT OSS 20B" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "nemotron-3-nano:30b", name: "Nemotron 3 Nano 30B" },
    { id: "nemotron-3-super", name: "Nemotron 3 Super" },
    { id: "nemotron-3-ultra", name: "Nemotron 3 Ultra" },
    { id: "gemma4:31b", name: "Gemma 4 31B" },
  ],
  serviceKinds: ["llm", "webFetch"],
  fetchConfig: {
    baseUrl: "https://ollama.com/api/web_fetch",
    method: "POST",
    authType: "apikey",
    authHeader: "bearer",
    formats: ["markdown"],
    maxCharacters: 200000,
    timeoutMs: 30000,
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
